### ISSUE TITLE
Notifications UI 

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#20]
Need to update the notifications UI to include the following:

- [x] Show in notification:  date, who it is from, and message. 
- [ ] Differentiate between read and unread messages
- [x] Delete button to delete message
- [x] Button design for action based notifications.  Initial use will be for accept or deny of team membership requests.

**Comment by DoctorSoup143** [comment]
I need a way to test and create notifications in order to test this fcuntionality.

**Comment by mphacker** [comment]
This is why I am waiting for the UI to be created for the Send Notification page.

**Comment by DoctorSoup143** [comment]
I dont think we need to differentiate between read and unread messages as users can delete messages manually now.

I also think we could have an "Invited To" table on the Edit Profile page under teams. This way we don't need buttons on the notification.

**Comment by mphacker** [comment]
Decided to not have read / unread functionality for now.
