### ISSUE TITLE
Events and Games Page

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#21]
Need to complete UI design for the events page.

Page should include:

- Next event
- List of games 
- List of upcoming events for each game

Decisions to be made:

- Do we link to a separate page to show the events for a game, or do we try to display them all on one page.  Maybe have an accordion control under a game that can be expanded to show upcoming events.
- How will we show past events?  Will that be a different page?

**Comment by DoctorSoup143** [comment]
I think we need to create a new page design for Events.razor. Currently it looks like this

```
<CurrentEvent />
<Upcoming />
<GamesList />
<EFTEventTypes />
```

I would like to automate the current and upcoming event. This way on the day of an event, the current event shows, and the upcoming changes to the next event that way competitors and viewers know when the next one is. The current event should not be visible until the day of the event.

I think we need to keep `<EFTEventTypes />` until we create all of the events officially, and then we can delete it. This way I have the documentation and rules for reference.

---

The `Upcoming.razor` component needs to be generated dynamically like how we create events. This way we can just start scheduling events, and this will automatically default to upcoming event.

---

GamesList.razor seems to be working appropriately with the functionality you added.

---

EFTEventTypes.razor needs some work and should be replaced with the events like explained in section 1.

**Comment by mphacker** [comment]
Removed game types for now.  Currently only showing upcoming events and games.

**Comment by mphacker** [comment]
Initial pass completes
