### ISSUE TITLE
Event Rules Page

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#22]
Need to build out UI for showing the rules for an event.
This will be a pretty basic page since the data is coming from the rules field in the events table.
Assume that the event rules will already be HTML formatted and will just need to be displayed on the page.

**Comment by DoctorSoup143** [comment]
I think for this we should add multiple Rule fields. This way we can title and body of a rules section and it will automatically format it.

**Comment by mphacker** [comment]
completes this for now with commit c83fcfc18f8143a98ffe41800d4f9a6ac564e586

Showing rules only on event sign up form
