### ISSUE TITLE
Event Staff Admin

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#24]
Need to create admin page to allow the association of specific people as staff for events.
Staff members include:

- Caster
- Game Master
- Organizer
- Support

Do we have any other staff role types that need to be displayed on a staff page?

Note:  Only Admins and Game Masters will have special authenticated access in the app.

**Comment by DoctorSoup143** [comment]
That should cover the list of staff member roles.

**Comment by mphacker** [comment]
This was added directly to the Events admin page as a control.
