### ISSUE TITLE
Account Admin

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#26]
Need to complete account Admin screen. 

- [x] Need ability to flag a person as an admin or a Game Master
- [ ] Need ability to reset a person's password
- [x] Need ability to delete an account
- [x] Need ability to lock account
- [x] Need ability to ban account

Locked account means user cannot login to the website.
Banned account means user cannot login to the website and all of their profile information is hidden from viewers.

Need to go back to API and ensure that banned account data is not provided back for anonymous "get" operations.

**Comment by DoctorSoup143** [comment]
Designed complete and pushed to main branch.

**Comment by DoctorSoup143** [comment]
Current admin controls below. I think automating users resetting their own passwords is a preferred and better option so we don't have to do it for people.

![image](https://github.com/DoctorSoup143/KTN-Dev/assets/22720037/16a0644c-9ce6-4903-9c36-c5329e07f688)

**Comment by mphacker** [comment]
This appears to be completed.  Admins are not resetting user's passwords.  We will be adding a way to do that with a "forgot my password" feature.
