### ISSUE TITLE
Profile Edit Page

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#27]
- We need a password confirmation box for changing the password.  This is needed to ensure people don't fat finger something and lock themselves out.

- We only need 1 button for saving profile changes and 1 for password change.  Having multiple buttons will confuse the users since the profile is a single entity and we won't be just saving parts of it back to the database.  Any changes they make is saved as a unit.

-Need to ensure that when a person tries to change their email we check for duplicates.

Need checkboxes to set the following:
- [x]   A)  ShowDiscordOnPublicProfile
- [x]   B)  ShowKickOnPublicProfile   (we may just make this required for now)
- [x]   C) ShowAllGamerTagsOnPublicProfile
- [x]   D) ShowAwardsOnPublicProfile [This should be default]
- [x]   E) ShowfullNameOnPulbicProfile
- [x]   F) ShowProfilePicOnPublicProfile [Address this later]

**Comment by DoctorSoup143** [comment]
Design completed and uploaded to main branch.

**Comment by DoctorSoup143** [comment]
Added Discord name and checkbox.

**Comment by DoctorSoup143** [comment]
ShowAwardsOnPublicProfile - will be always enabled and we will not give users control of this future implementation.

---

ShowProfilePicOnPublicProfile - This we can add later. Once Kick has an API, maybe we can pull this automatically. I don't want nudity on these profiles.

**Comment by mphacker** [comment]
Page not completed.  Reopening until this works.

**Comment by mphacker** [comment]
@DoctorSoup143 There are no labels for the email and email confirmation text boxes.  It is a bit confusing as to what a user is supposed to be doing with them.

**Comment by DoctorSoup143** [comment]
Labels added.
