### ISSUE TITLE
Fields and button missing on Profile Edit Page

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#37]
Missing 3 form components on profile edit page:

1. Discord ID
2. check box for "show on profile" for Discord.
3. Save button under Gamer Tags to save profile updates.

Question:  The Change Password and Change Email sections need their own save buttons.  If the profile save button is under the Gamer tags section, is that confusing?   Could people think that if they enter in a new password or change their email and hit the save button at the bottom that it would also change their email or password?  Maybe we need to simplify this down to a single button press instead of 3 different buttons.

**Comment by DoctorSoup143** [comment]
Removed the 2 save buttons and added a "Save All" under the gamertag section to simplify.
