### ISSUE TITLE
Accounts With Duplicate Names

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#38]
How will we handle people who create account names for other users? 

What if a user creates an account as another, more popular, creator?

What if someone creates 2 accounts with the same name?

How will we handle duplicates?

**Comment by mphacker** [comment]
Accounts are already unique based on email.  Any of the other data including name, kick account, etc... can be duplicated.  

If you receive feedback that someone is using another person's kick name or identity then you will need a policy to address it.
