### ISSUE TITLE
Update Staff Member Page

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#44]
Add OldPeeps to staff member page as a Partner/Sponsor

**Comment by mphacker** [comment]
Will this be on a "Staff" page for all KTN events or should he just be part of the staff page for specific events?  I don't think we have a Partner / Sponsor role for staff.  Maybe that is something we should add.

**Comment by DoctorSoup143** [comment]
His card will be placed next to yours. No specific roles required or anything. He will have the website role of a Gamemaster
