### ISSUE TITLE
Teams Issues

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#45]
Should Teams only exist for a specific event, or should a team live on forever and can be used across multiple events?

Currently we have it setup that a team is created for a specific event.

Would people want to create a team that participates across multiple events?

I don't believe we have a max number of team members identified.  This could be set at the event level if we have teams aligned to events.  If we don't have teams aligned to specific events then we may not want to have any sort of team size limit.

If we have teams living beyond events then we would need a way for the team captain to indicate which of their team members will be participating in an event since the team may have more people than available player spots in an event.

**Comment by DoctorSoup143** [comment]
Probably specific events. This way were not storing tons of teams on a DB.

**Comment by mphacker** [comment]
Completed - Teams are associated with specific events.
