### ISSUE TITLE
Add Twitch Fields to Account

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#49]
@DoctorSoup143 

Update the profile page to accommodate a Twitch name and Link.

- [x] Add Twitch name.
- [x] Add Twitch link.
- [x] Add "Show on Profile" checkbox.

---

@mphacker 

Design functionality and required database structure to accommodate new Twitch fields.

**Comment by DoctorSoup143** [comment]
Ready for functionality.

**Comment by mphacker** [comment]
We have based registration requirements and account searching based on KickName.  How is this going to be handled going forward?   
Do we allow either Kick or Twitch during registration?  
When searching for a user by name (profile search, and other locations) how do we handle a situation where the same name is used on Twitch and Kick but by different people?

**Comment by DoctorSoup143** [comment]
### Edit Profile
I think we need to make the edit profile page only allow to show either Kick or Twitch, not both. The shown username would need to be the username that's searchable and the one used for score tracking.

---

### Account Registration
For Kick and Twitch users, we would need to make the Kick and Twitch fields optional on the signup form, but also add a radio button selection that's required for them to select to use either the Twitch or Kick usernames. This way, when creating an account, they have to select what username they want to use. That would fix the search issue and allow us to not allow duplicates while populating all fields.

---

I will modify the signup page to include these radio buttons on my next update.

**Comment by DoctorSoup143** [comment]
Different approach taken.
