### ISSUE TITLE
Game Platform

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#52]
Should we have a field that ties to a game, event type or event that identifies what platform this is on.  For example:  

Tarkov,
Battlenet
Steam

Doing this would allow us to show the correct gamertag on the event sign-up page based on the event.  This could also allow you to prevent registration if they haven't filled out the correct gamertag in their profile.

**Comment by DoctorSoup143** [comment]
I think this would be a great implementation for signups. That way we can, like you said, show the correct gamertag and information for events and have it tie to the list of people who've signed up.
