### ISSUE TITLE
Block individual signup for Team events

### ISSUE THREAD

**Issue by mphacker** [DoctorSoup143/KTN-Dev#56]
Prevent a user from registering for a team based event if they are not already part of a team associated with that event.

May want to have some sort of tool tip / hint / or other information on the event card to indicate why they are unable to sign up.  

One possible option is to disable the sign up button and have a tool tip pop up when they mouse over that explains they need to join a team.

**Comment by mphacker** [comment]
Completed.  @DoctorSoup143  - can you style the disabled button to make it more obvious a person is not able to register?

**Comment by DoctorSoup143** [comment]
Changed button design with disabled tag.
