### ISSUE TITLE
Delete Upcoming Events

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#72]
We need a functionality to delete upcoming events that have not started. This allows us to cancel events ahead of time and not compromise previous scoring. Additionally, we should remove controls from historical events to prevent deletion.

---

- [ ] Create "Previous Events" list in the admin page for Events.
- [ ] Repurpose existing table for Upcoming Events only.
- [ ] Remove delete and edit option from Previous events.

**Comment by mphacker** [comment]
Change - Edit button will be in the previous events list

**Comment by mphacker** [comment]
Completed
