### ISSUE TITLE
Show Roles On Profile

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#74]
Show the admin roles on user profiles.

List of roles:

- [ ] User (No Roles)
- [ ] Gamemaster (Validator)
- [ ] Admin (Admin)

---

Added to the profile page. It currently says "User".

**Comment by mphacker** [comment]
@DoctorSoup143  - How about having some sort of icon / logo for Admin, Caster and Gamemaster for their profiles?

**Comment by DoctorSoup143** [comment]
With an event staff page I feel like this would be moot. If we show permissions on profile then users cant claim to be something the'yre not. It also allows users to pinpoint who admins are on the website.

**Comment by mphacker** [comment]
I just thought it would look cool with some sort of badge or icon on the profile page that represent "admin" or "gamemaster" instead of just the words

**Comment by mphacker** [comment]
done
