### ISSUE TITLE
Create Event Sign-Up Form

### ISSUE THREAD

**Issue by DoctorSoup143** [DoctorSoup143/KTN-Dev#8]
Create sign-up forms for all Tarkov events.

- [ ] Takedown Tournament
- [ ] Kill Confirmed
- [ ] Kalashnikov Clash
- [ ] Western Showdown
- [ ] Mall Cops
- [ ] Limitless Legion

**Comment by mphacker** [comment]
There will be a single event registration form for a user that will work across all games and event types.  Under forms this is the EventSignupForm.   This is a work in progress and needs to be completed.

**Comment by mphacker** [comment]
Completed.
